### PR TITLE
Fix the bug that files were not streamed asynchronously

### PR DESCRIPTION
**Pull request by d-hayashi**
## What?
Fix dataware-tools/dataware-tools#69  
- Run multiple workers in parallel 
- Fix the bug that function `_shout_stream` was not working asynchronously

## Why?
To prevent request timeouts

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/api-file-provider/pull/25#" title="Author self-approved">d-hayashi</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapi-file-provider).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/api-file-provider/blob/master/OWNERS)~~ [d-hayashi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by WatanabeToshimitsu** [comment]
一応色々調べてみたんですが，未だに「何故ファイルを配信する処理にスレッドが占有されてしまうのか」が分かっておらず...
responder やら Starlette のソースコードを見てみても，[ネットワークストリームを通して通信する部分は非同期処理になっている](https://github1s.com/encode/starlette/blob/HEAD/starlette/responses.py#L204-L205)ようで，仮にファイル送信中にリクエストが来ても，それをファイルの送信と並行して処理できるように思えます
この辺りに関して，理解できそうな記述ご存知でしょうか？

**Comment by d-hayashi** [comment]
よくよく調べてみたら単純に `_shout_stream` 関数の中で非同期処理に対応していない `open()` 関数を使っていたがためにファイルのダウンロード部分が非同期処理になっていなかったのが原因でした。。

(参考)
https://www.twilio.com/blog/working-with-files-asynchronously-in-python-using-aiofiles-and-asyncio

**Review by WatanabeToshimitsu — APPROVED** [review]
LGTM !

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/api-file-provider/pull/25#" title="Author self-approved">d-hayashi</a>*, *<a href="https://github.com/dataware-tools/api-file-provider/pull/25#pullrequestreview-735752392" title="Approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapi-file-provider).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/api-file-provider/blob/master/OWNERS)~~ [WatanabeToshimitsu,d-hayashi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
